
package soapclient.airline.flight;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8001/airlineMTA/FlightWS?wsdl")
public class FlightWS_Service
    extends Service
{

    private final static URL FLIGHTWS_WSDL_LOCATION;
    private final static WebServiceException FLIGHTWS_EXCEPTION;
    private final static QName FLIGHTWS_QNAME = new QName("http://soap/", "FlightWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/airlineMTA/FlightWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTWS_WSDL_LOCATION = url;
        FLIGHTWS_EXCEPTION = e;
    }

    public FlightWS_Service() {
        super(__getWsdlLocation(), FLIGHTWS_QNAME);
    }

    public FlightWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTWS_QNAME, features);
    }

    public FlightWS_Service(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTWS_QNAME);
    }

    public FlightWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTWS_QNAME, features);
    }

    public FlightWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightWS
     */
    @WebEndpoint(name = "FlightWSPort")
    public FlightWS getFlightWSPort() {
        return super.getPort(new QName("http://soap/", "FlightWSPort"), FlightWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightWS
     */
    @WebEndpoint(name = "FlightWSPort")
    public FlightWS getFlightWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "FlightWSPort"), FlightWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTWS_EXCEPTION!= null) {
            throw FLIGHTWS_EXCEPTION;
        }
        return FLIGHTWS_WSDL_LOCATION;
    }

}
