
package soapclient.airline.flight;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightWS {


    /**
     * 
     * @param idFlightSearch
     * @return
     *     returns soapclient.airline.flight.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlight", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlight")
    @ResponseWrapper(localName = "searchFlightResponse", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightResponse")
    @Action(input = "http://soap/FlightWS/searchFlightRequest", output = "http://soap/FlightWS/searchFlightResponse")
    public SoapResponse searchFlight(
        @WebParam(name = "idFlightSearch", targetNamespace = "")
        long idFlightSearch);

    /**
     * 
     * @param idFlightInstance
     * @return
     *     returns soapclient.airline.flight.FlightInstanceDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightInstace", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightInstace")
    @ResponseWrapper(localName = "searchFlightInstaceResponse", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightInstaceResponse")
    @Action(input = "http://soap/FlightWS/searchFlightInstaceRequest", output = "http://soap/FlightWS/searchFlightInstaceResponse")
    public FlightInstanceDTO searchFlightInstace(
        @WebParam(name = "idFlightInstance", targetNamespace = "")
        long idFlightInstance);

    /**
     * 
     * @param paramSearch
     * @return
     *     returns java.util.List<soapclient.airline.flight.FlightDataListSOAP>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlights", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlights")
    @ResponseWrapper(localName = "searchFlightsResponse", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightsResponse")
    @Action(input = "http://soap/FlightWS/searchFlightsRequest", output = "http://soap/FlightWS/searchFlightsResponse")
    public List<FlightDataListSOAP> searchFlights(
        @WebParam(name = "paramSearch", targetNamespace = "")
        ParamFlightSOAP paramSearch);

    /**
     * 
     * @param idFlightInstance
     * @return
     *     returns soapclient.airline.flight.FlightInstanceDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightInstace", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightInstace")
    @ResponseWrapper(localName = "searchFlightInstaceResponse", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightInstaceResponse")
    @Action(input = "http://soap/FlightWS/searchFlightInstaceRequest", output = "http://soap/FlightWS/searchFlightInstaceResponse")
    public FlightInstanceDTO searchFlightInstace(
        @WebParam(name = "idFlightInstance", targetNamespace = "")
        long idFlightInstance);

    /**
     * 
     * @param idReservation
     * @return
     *     returns java.util.List<soapclient.airline.flight.IdFlightInstanceWithSeatsDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightsByReservation", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightsByReservation")
    @ResponseWrapper(localName = "searchFlightsByReservationResponse", targetNamespace = "http://soap/", className = "soapclient.airline.flight.SearchFlightsByReservationResponse")
    @Action(input = "http://soap/FlightWS/searchFlightsByReservationRequest", output = "http://soap/FlightWS/searchFlightsByReservationResponse")
    public List<IdFlightInstanceWithSeatsDTO> searchFlightsByReservation(
        @WebParam(name = "idReservation", targetNamespace = "")
        long idReservation);

}
